name = "DifferentialDynamicProgramming"
uuid = "9cd584b6-1a68-5b24-b787-24af5fbbf48b"
author = "Fredrik Bagge Carlson <baggepinnen@gmail.com>"
repo = "https://github.com/baggepinnen/DifferentialDynamicProgramming.jl.git"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
